{!!Html::script('theme/vue/js/app.js')!!}
{!!Html::script('theme/js/nprogress.js')!!}
{!!Html::script('theme/js/bootstrap.min.js')!!}
{!!Html::script('theme/js/progressbar/bootstrap-progressbar.min.js')!!}
{!!Html::script('theme/js/icheck/icheck.min.js')!!}
{!!Html::script('theme/js/select/select2.full.js')!!}
{!!Html::script('theme/js/switchery/switchery.min.js')!!}
{!!Html::script('theme/js/moment/moment.min.js')!!}
{!!Html::script('theme/js/custom.js')!!}
{!!Html::script('theme/js/wizard/jquery.smartWizard.js')!!}
{!!Html::script('theme/js/pace/pace.min.js')!!}
{!!Html::script('theme/js/skycons/skycons.min.js')!!}
{!!Html::script('theme/js/jquery.colorbox.js')!!}
{!!Html::script('theme/js/notify/pnotify.core.js')!!}
{!!Html::script('theme/js/notify/pnotify.buttons.js')!!}
{!!Html::script('theme/js/notify/pnotify.nonblock.js')!!}
{!!Html::script('theme/js/msgbox/jquery.msgbox.js')!!}
{!!Html::script('theme/js/datepicker/daterangepicker.js')!!}

